### User dependent configuration, may contain potentially sensitive data (thus part of .gitignore). Values are configurable by the cli or through manual editing

# The top level directory path containing the container Android source code
android_src_root: TODO
# Directory path layouts
android_layout_root: TODO
# Directory path drawables
android_drawable_root: TODO
# Directory path strings
android_string_root: TODO
# The top level directory of the container application project
container_git_root: TODO
# main/master branch name of the container
container_main_branch_name: main
# ___ which will be added to the tagname to make the new container branch we are migrating to distinguishable from the original fork tag. Fit it to your project.
migration_branch_subscript: TODO_
# The top level directory of the subrepository, embedded into the container (must be a subdirectory of <android_src_root>)
feature_git_root: TODO
# A directory in which the feature repository will be checked out for automated git operations. Should have write access.
feature_git_temp_root: TODO
# https url (e.g., Github) of the feature
feature_git_remote: TODO
# Used to automate branching to remote for migration
github_username: TODO
# Strongly recommended to create a fine grained token that only provides access to the feature repository, as this will show up in local logs and bash history.
feature_github_access_token: TODO
# The marker used in the container wherever feature code is integrated. Used to extract the contact points.
marker: TODO
# The path to *this*/.. directory. CLI expects this as the working dir.
python_root: TODO
# Where to create the runtime and error logs
working_dir: TODO
# Flag to pass to git subrepo, reflected in logging
subrepo_verbosity: -dv
# Flag for Git
git_verbosity: -v
# indicates if we are running a Linux emulation under windows (needed for path remaps in 'git' code). False is correct for most users.
windows: False
# Where to insert matching context. -1 => before the insert, 1 => after the insert
diff_context: 1
# The number of lines to grab for the context. Will grab *at most* this many non-whitespace lines.
diff_context_lines: 5
# Any files that cannot be marked with a comment (e.g, .pngs) but still need to be extracted. Provided as a yaml array. These will be pure copy by default.
additional_extraction_file_paths:  None
# The corresponding contact point paths where these should be stored in order of appearance. These will be pure copy by default.
additional_extraction_file_contact_point_paths: None
